[package]
name = "minirand"
version = "0.1.0"
edition = "2024"

[dependencies]
panics = { path = "../panic"}

[lib]
crate-type = ["rlib", "dylib", "staticlib"]
[features]
default = ["cycles"]
cycles = []