[package]
name = "cuda_subst"
authors.workspace = true
repository.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
libc = "0.2.177"
rand = "0.9.2"

[lints]
workspace = true

[build-dependencies]
cc = "1.2.48"
